[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solation = "2KW4NXTSbeq5BJM39rsR1sR15Uf72perBkVVMH88ZGRm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = 'C:\Users\sk_16\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
